#!/usr/bin/env bash

set -ex

cat << EOF > /etc/dhcp/dhclient.conf
supersede domain-name-servers 10.0.0.2;
supersede domain-name " ";
EOF

cat << EOF > /etc/tor/torrc
DataDirectory /var/lib/tor
RunAsDaemon 1
User debian-tor

VirtualAddrNetwork 10.192.0.0/10
AutomapHostsOnResolve 1
TransPort 10.0.0.2:9040
DNSPort 10.0.0.2:53
SocksPort 10.0.0.2:9050
ControlPort 127.0.0.1:9051
EOF

ip netns add clearnet
for IFACE in $(ls -1 /sys/class/net | grep '^e'); do
    ip link set dev "${IFACE}" netns clearnet
    ip netns exec clearnet macchanger -A "${IFACE}"
done
for IFACE in $(iw list | grep Wiphy | cut -d" " -f2); do
    iw phy "${IFACE}" set netns name clearnet
done
for IFACE in $(ip netns exec clearnet ls -1 /sys/class/net | grep '^w'); do
    ip netns exec clearnet ip link set "${IFACE}" down
    ip netns exec clearnet macchanger -A "${IFACE}"
done

ip netns exec clearnet ip link add tor0 type veth peer name tor0 netns 1
ip addr add 10.0.0.1/24 dev tor0
ip netns exec clearnet ip addr add 10.0.0.2/24 dev tor0
ip link set tor0 up
ip netns exec clearnet ip link set tor0 up
ip netns exec clearnet ip link set lo up
ip route add default via 10.0.0.2

ip netns exec clearnet iptables -F
ip netns exec clearnet iptables -t nat -F
ip netns exec clearnet iptables -t nat -A PREROUTING -i tor0 -p udp --dport 53 -j REDIRECT --to-ports 53
ip netns exec clearnet iptables -t nat -A PREROUTING -i tor0 -p tcp --syn -j REDIRECT --to-ports 9040

sysctl -w net.ipv4.conf.all.forwarding=1

ip netns exec clearnet dhclient
cat << EOF > /etc/resolv.conf
nameserver 1.1.1.1
EOF
ip netns exec clearnet timeout 5s /lib/systemd/systemd-timesyncd || true
cat << EOF > /etc/resolv.conf
nameserver 10.0.0.2
EOF
ip netns exec clearnet tor
ip netns exec clearnet /lib/systemd/systemd-timesyncd &
